import { sql } from "drizzle-orm";
import { mysqlTable, text, varchar, timestamp, boolean, int } from "drizzle-orm/mysql-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = mysqlTable("users", {
  id: varchar("id", { length: 36 }).primaryKey(),
  username: varchar("username", { length: 255 }).notNull().unique(),
  password: text("password").notNull(),
  email: varchar("email", { length: 255 }),
  displayName: varchar("display_name", { length: 255 }),
  role: varchar("role", { length: 50 }).default("reader"), // admin, author, reader
  createdAt: timestamp("created_at").defaultNow(),
});

export const categories = mysqlTable("categories", {
  id: varchar("id", { length: 36 }).primaryKey(),
  name: varchar("name", { length: 255 }).notNull().unique(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  description: text("description"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const posts = mysqlTable("posts", {
  id: varchar("id", { length: 36 }).primaryKey(),
  title: varchar("title", { length: 500 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  excerpt: text("excerpt"),
  content: text("content").notNull(),
  featuredImage: varchar("featured_image", { length: 500 }),
  authorId: varchar("author_id", { length: 36 }).references(() => users.id),
  categoryId: varchar("category_id", { length: 36 }).references(() => categories.id),
  sourceLink: varchar("source_link", { length: 1000 }),
  // Whether comments are disabled for this post (e.g. generated/auto posts)
  commentsDisabled: boolean("comments_disabled").default(false),
  // Mark posts that were generated by the AI agent
  generated: boolean("generated").default(false),
  published: boolean("published").default(false),
  publishedAt: timestamp("published_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const comments = mysqlTable("comments", {
  id: varchar("id", { length: 36 }).primaryKey(),
  postId: varchar("post_id", { length: 36 }).references(() => posts.id),
  authorId: varchar("author_id", { length: 36 }).references(() => users.id),
  content: text("content").notNull(),
  parentId: varchar("parent_id", { length: 36 }), // for nested comments - will be validated in application logic
  createdAt: timestamp("created_at").defaultNow(),
});

export const postTags = mysqlTable("post_tags", {
  id: varchar("id", { length: 36 }).primaryKey(),
  postId: varchar("post_id", { length: 36 }).references(() => posts.id),
  tag: varchar("tag", { length: 100 }).notNull(),
});

export const apiKeys = mysqlTable("api_keys", {
  id: varchar("id", { length: 36 }).primaryKey(),
  userId: varchar("user_id", { length: 36 }).references(() => users.id),
  name: varchar("name", { length: 255 }).notNull(),
  keyHash: text("key_hash").notNull(),
  permissions: text("permissions"), // JSON string of permissions
  expiresAt: timestamp("expires_at"),
  lastUsedAt: timestamp("last_used_at"),
  createdAt: timestamp("created_at").defaultNow(),
  usageCount: int("usage_count").default(0),
});

export const autoPostsQueue = mysqlTable("auto_posts_queue", {
  id: varchar("id", { length: 36 }).primaryKey(),
  title: varchar("title", { length: 500 }).notNull(),
  slug: varchar("slug", { length: 255 }).notNull().unique(),
  content: text("content").notNull(),
  excerpt: text("excerpt"),
  // Optional category id for the queued item (references categories.id)
  categoryId: varchar("category_id", { length: 36 }),
  featuredImage: varchar("featured_image", { length: 500 }),
  sourceLink: varchar("source_link", { length: 1000 }),
  tags: text("tags"), // JSON array
  autoPublish: boolean("auto_publish").default(false),
  status: varchar("status", { length: 50 }).default("queued"), // queued, reviewed, published, failed
  createdAt: timestamp("created_at").defaultNow(),
  processedAt: timestamp("processed_at"),
});

export const sourceValidationLogs = mysqlTable("source_validation_logs", {
  id: varchar("id", { length: 36 }).primaryKey(),
  postId: varchar("post_id", { length: 36 }).references(() => posts.id),
  ok: boolean("ok").default(false),
  reason: text("reason"),
  checkedAt: timestamp("checked_at").defaultNow(),
  checkedBy: varchar("checked_by", { length: 255 })
});

export const aiSettings = mysqlTable("ai_settings", {
  key: varchar("key", { length: 255 }).primaryKey(),
  value: text("value"),
  createdAt: timestamp("created_at").defaultNow(),
});

// Use explicit insert types to avoid complex inferred types from drizzle-zod
export type InsertUser = {
  username: string;
  password: string;
  email?: string | null;
  role?: string;
};

export type InsertCategory = {
  name: string;
  slug: string;
  description?: string | null;
};

export type InsertPost = {
  title: string;
  slug: string;
  excerpt?: string | null;
  content: string;
  featuredImage?: string | null;
  authorId?: string | null;
  sourceLink?: string | null;
  categoryId?: string | null;
  published?: boolean;
  generated?: boolean;
  commentsDisabled?: boolean;
};

export type InsertComment = {
  postId: string;
  authorId?: string | null;
  content: string;
  parentId?: string | null;
};

export type InsertPostTag = {
  postId: string;
  tag: string;
};

export type InsertApiKey = {
  userId: string;
  name: string;
  keyHash: string;
  permissions?: string | null;
  expiresAt?: Date | null;
};

export type User = typeof users.$inferSelect;
export type Category = typeof categories.$inferSelect;
export type Post = typeof posts.$inferSelect;
export type Comment = typeof comments.$inferSelect;
export type PostTag = typeof postTags.$inferSelect;
export type ApiKey = typeof apiKeys.$inferSelect;
export type SourceValidationLog = typeof sourceValidationLogs.$inferSelect;
