name: CI - Node Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Show basic workspace
        run: |
          echo "PWD: $(pwd)"
          ls -la

      - name: Install dependencies
        run: npm ci
        working-directory: blogmastermind

      - name: Run build
        run: npm run build
        working-directory: blogmastermind

      - name: Upload possible npm debug log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-log
          path: |
            blogmastermind/npm-debug.log
            blogmastermind/.npm/_logs/**
