name: CI - Docker Build (BuildKit)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub (optional)
        if: false
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with BuildKit (plain logs)
        env:
          DOCKER_BUILDKIT: 1
        run: |
          cd blogmastermind
          echo "Starting docker build with BuildKit..."
          DOCKER_BUILDKIT=1 docker build --progress=plain -t testcraftworld:ci -f Dockerfile . | tee build-output.log

      - name: Upload docker build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-output
          path: blogmastermind/build-output.log
